name: Gradle Build
on:
  workflow_dispatch:

jobs:
  gradle:
    name: Gradle Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set Secret Properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > ./local.properties
      - name: Prepare release keystore
        run: |
          echo "${{ secrets.BASE_64_SIGNING_KEY }}" > release_keystore.jks.asc
          gpg -d --passphrase "${{ secrets.BASE_64_SIGNING_KEY_PASSPHRASE }}" --batch release_keystore.jks.asc > app/release_keystore.jks
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build release artifact
        run: ./gradlew assembleRelease
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/
