name: Gradle Build
on:
  workflow_dispatch:

jobs:
  gradle:
    name: Gradle Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/
